# Generated by Django 5.1.6 on 2025-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quentity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
